### PR TITLE
Add latest discord.py commit to requirements

### LINKED ISSUE #4: use latest discord.py instead of release
So we can get thread goodies!

### PR DESCRIPTION
**Pull request by rissajackson**
closes #4

### CODE REVIEW

**Comment by andyshinn** [comment]
Let me know if you want help with the failure. It will need something added to the `Dockerfile`.

**Comment by rissajackson** [comment]
> Let me know if you want help with the failure. It will need something added to the `Dockerfile`.

Yes please! 😄

**Comment by andyshinn** [comment]
😮

**Review by andyshinn — APPROVED** [review]
👍

**Review by mrooney — COMMENTED** [review]
Looks great!

**Pull request merged**
